# In ticks. 30 minutes by default
dtr-regen: 36000

use-kits: true

format-chat: true
formatted-chat: §8[{team}§8]§f{name}§8 » §7{message}
formatted-chat-no-team-found-for-player: §f{name}§8 » §7{message}

minimumClaimWidth: 4
maximumClaimCornerDistance: 40
aggressiveMobSpawningInClaims: false

maxDescriptionLength: 80